version: '3.8'
services:
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=mpl_ulab_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2